### PR TITLE
Switch to double quotes for tag attribute values

### PR DESCRIPTION
**Pull request by aidalgol**
While single quotes around attribute values is valid HTML and XML, the
more common convention is to use double quotes; since there is
no (major) advantage to either, it seems best to go with the more
common convention, for the sake of consistency.

### CODE REVIEW

**Comment by nicferrier** [comment]
Oi. doesn't this break a SHED load of tests?

**Comment by aidalgol** [comment]
Indeed it does.  Forgot about the tests.  I'll make the `' -> "` changes to the tests, too, and then prod you about this again.

BTW, nice response time. ;)

**Comment by aidalgol** [comment]
OK, fixed now.

**Comment by nicferrier** [comment]
This has got merge failures now... sorry, probably my fault but I'll merge this if you fix up the conflict. Thanks!

**Comment by aidalgol** [comment]
Hosed by changes in upstream.  Will redo later.

**Pull request closed without merging**
